# Generated by Django 4.0.4 on 2022-05-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
